# Generated by Django 5.2.1 on 2025-07-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srldc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table2adata',
            old_name='act_drawal',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='table2adata',
            old_name='consumption',
            new_name='demand_met',
        ),
        migrations.RenameField(
            model_name='table2adata',
            old_name='drawal_sch',
            new_name='drawal',
        ),
        migrations.RenameField(
            model_name='table2adata',
            old_name='other_biomass_co_gen_etc',
            new_name='net_sch',
        ),
        migrations.RenameField(
            model_name='table2adata',
            old_name='requirement',
            new_name='others',
        ),
    ]
