# Generated by Django 5.2.1 on 2025-08-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srldc', '0002_rename_act_drawal_table2adata_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table2cdata',
            old_name='demand_met_at_max_requirement',
            new_name='demand_met_max_requirement',
        ),
        migrations.RenameField(
            model_name='table2cdata',
            old_name='max_requirement_of_the_day',
            new_name='maximum_requirement_day',
        ),
        migrations.RenameField(
            model_name='table2cdata',
            old_name='time_max_demand_met',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='table2cdata',
            name='min_demand_met',
        ),
        migrations.RemoveField(
            model_name='table2cdata',
            name='time_min_demand_met',
        ),
    ]
