# Generated by Django 5.2.1 on 2025-08-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srldc', '0003_rename_demand_met_at_max_requirement_table2cdata_demand_met_max_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table2cdata',
            name='min_demand_met',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table2cdata',
            name='time_min_demand_met',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
