# Generated by Django 5.2.1 on 2025-08-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srldc', '0004_table2cdata_min_demand_met_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table2cdata',
            old_name='maximum_requirement_day',
            new_name='max_requirement_day',
        ),
        migrations.RemoveField(
            model_name='table2cdata',
            name='min_demand_met',
        ),
        migrations.RemoveField(
            model_name='table2cdata',
            name='time_min_demand_met',
        ),
    ]
